### ISSUE TITLE
Fix invite link in Join Lobby

### ISSUE THREAD

**Issue by Kipstz** [openfrontio/OpenFrontIO#1694]
Currently when you paste the invitation ( https://openfront.io#join=QwIr5aK4 ) it puts undefined in the input so I made this issue to make a PR and fix the problem.

<img width="410" height="370" alt="Image" src="https://github.com/user-attachments/assets/89cc2e52-afea-4a39-8e11-577467468fe4" />

**Comment by Duwibi** [comment]
Already fixed in #1634

**Comment by Kipstz** [comment]
@Duwibi the PR in question was merged on the 30th but still not functional the problem persists

**Comment by Kipstz** [comment]
And just to clarify, I've just checked your PR, which has nothing to do with the problem described above.

**Comment by Duwibi** [comment]
> And just to clarify, I've just checked your PR, which has nothing to do with the problem described above.
> 

It has a lot to do with the problem. It prevents a link that doesn't have a slash from being copied in the first place. But, It's not really important, as this PR was already merged and the issue is basically double solved (from both the side of the link being created, and the false link being used).

**Comment by Duwibi** [comment]
> @Duwibi the PR in question was merged on the 30th but still not functional the problem persists

It being non-functional probably has something to do with the PR not being pushed to .io yet. Both PRs will be pushed at the same time
